repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3.7
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.5.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3.7
        files: '^((?!README).)*\.md$'
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "hypothesis_bio:."]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        exclude: .*/__init__.py
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 18.8.0"]
        language_version: python3.7
    - id: check-merge-conflict
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.3.0
    hooks:
      - id: python-no-log-warn
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.12.0
    hooks:
    -   id: pyupgrade
