name: Build documentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Build site
        run: cd docs && pip install -r requirements.txt && npm install && npm run build && cp -r .vuepress/dist ../dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
